__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: '2016-01-08'
    date_last_updated: 
    Kronos_version: '2.0.3'
__GENERAL__: 
    bwa: 'bwa'
    samtools: 'samtools'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'bwa_mem'
        component_version: 'v1.0.0'
        seed_version: 'v0.7.10'
    run: 
        use_cluster: False
        memory: '10G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
        parallel_run: False
        parallel_params: []
        interval_file: 
    component: 
        input_files: 
            fastq_1: '__REQUIRED__'
            input_dir: '__OPTIONAL__'
            fastq_2: '__OPTIONAL__'
            reference: '__REQUIRED__'
        output_files: 
            output_bam: '__REQUIRED__'
            output_dir: '__OPTIONAL__'
        parameters: 
            num_threads: '__OPTIONAL__'
