__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: '2016-01-08'
    date_last_updated: 
    Kronos_version: '2.0.3'
__GENERAL__: 
    python: 'python'
    split_fastq.py: '__REQUIRED__'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'split_fastq'
        component_version: 'v1.0.0'
        seed_version: 'v1.1.4'
    run: 
        # NOTE: component cannot run in parallel mode.
        use_cluster: False
        memory: '1G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            fastq_files: '__REQUIRED__'
        output_files: 
            interval_file: '__OPTIONAL__'
            output_dir: '__OPTIONAL__'
        parameters: 
            no_compression: False
            num_buffer: 5000000
            no_symlink: False
            num_reads: 75000000
