__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: 
    date_last_updated: 
    factory_version: '1.11.2'
__GENERAL__: 
    picard_binary: '__REQUIRED__'
    java_binary: '__REQUIRED__'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'picard_mark_duplicates'
        component_version: 'v1.0.0'
        seed_version: '1.136'
    run: 
        # NOTE: component cannot run in parallel mode.
        use_cluster: False
        memory: '3G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            INPUT: '__REQUIRED__'
            REFERENCE_SEQUENCE: '__OPTIONAL__'
        output_files: 
            OUTPUT: '__REQUIRED__'
            METRICS_FILE: '__REQUIRED__'
            TMP_DIR: '__OPTIONAL__'
        parameters: 
            PROGRAM_GROUP_VERSION: '__OPTIONAL__'
            REMOVE_DUPLICATES: '__FLAG__'
            DUPLICATE_SCORING_STRATEGY: '__OPTIONAL__'
            VERBOSITY: '__OPTIONAL__'
            QUIET: '__FLAG__'
            SORTING_COLLECTION_SIZE_RATIO: '__OPTIONAL__'
            OPTICAL_DUPLICATE_PIXEL_DISTANCE: '__OPTIONAL__'
            MAX_RECORDS_IN_RAM: '__OPTIONAL__'
            COMMENT: '__OPTIONAL__'
            picard_command: 'MarkDuplicates'
            PROGRAM_GROUP_COMMAND_LINE: '__OPTIONAL__'
            PROGRAM_GROUP_NAME: '__OPTIONAL__'
            CREATE_MD5_FILE: '__FLAG__'
            ASSUME_SORTED: '__FLAG__'
            CREATE_INDEX: '__FLAG__'
            READ_NAME_REGEX: '__OPTIONAL__'
            VALIDATION_STRINGENCY: '__OPTIONAL__'
            java_memory: '__OPTIONAL__'
            PROGRAM_RECORD_ID: '__OPTIONAL__'
            COMPRESSION_LEVEL: '__OPTIONAL__'
            MAX_FILE_HANDLES_FOR_READ_ENDS_MAP: '__OPTIONAL__'
            GA4GH_CLIENT_SECRETS: '__OPTIONAL__'
