__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: '2015-12-16'
    date_last_updated: 
    Kronos_version: '2.0.3'
__GENERAL__: 
    vcf2maf.pl: '__REQUIRED__'
    perl_binary: '__REQUIRED__'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'vcf2maf_1_5_4'
        component_version: 'v1.0.0'
        seed_version: '1.5.4'
    run: 
        # NOTE: component cannot run in parallel mode.
        use_cluster: False
        memory: '10G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            vep_data: '__OPTIONAL__'
            snpeff_path: '__OPTIONAL__'
            ref_fasta: '__OPTIONAL__'
            vep_path: '__OPTIONAL__'
            snpeff_data: '__OPTIONAL__'
            input_snpeff: '__OPTIONAL__'
            input_vep: '__OPTIONAL__'
            custom_enst: '__OPTIONAL__'
            input_vcf: '__OPTIONAL__'
        output_files: 
            output_maf: '__OPTIONAL__'
        parameters: 
            use_snpeff: '__OPTIONAL__'
            ncbi_build: '__OPTIONAL__'
            maf_center: '__OPTIONAL__'
            vcf_tumor_id: '__OPTIONAL__'
            min_hom_vaf: '__OPTIONAL__'
            vep_forks: '__OPTIONAL__'
            tumor_id: '__OPTIONAL__'
            normal_id: '__OPTIONAL__'
            snpeff_db: '__OPTIONAL__'
            vcf_normal_id: '__OPTIONAL__'
