__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: '2016-01-08'
    date_last_updated: 
    Kronos_version: '2.0.3'
__GENERAL__: 
    star_binary: '__REQUIRED__'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'star'
        component_version: 'v1.0.0'
        seed_version: '2.4.1d'
    run: 
        # NOTE: component cannot run in parallel mode.
        use_cluster: False
        memory: '6G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            sjdbFileChrStartEnd: '__OPTIONAL__'
            genomeDir: '__OPTIONAL__'
            readFilesIn: '__OPTIONAL__'
        output_files: 
            outFileNamePrefix: '__OPTIONAL__'
        parameters: 
            readFilesCommand: '__OPTIONAL__'
            outSAMtype: '__OPTIONAL__'
            runThreadN: '__OPTIONAL__'
            outSAMmode: '__OPTIONAL__'
            sjdbOverhang: '__OPTIONAL__'
