"""
component_params.py

@author: bgrande
"""


input_files = {"input_file": "__REQUIRED__",
               "dir": "__OPTIONAL__",
               "dir_cache": "__OPTIONAL__",
               "dir_plugins": "__OPTIONAL__"}

output_files = {"output_file": "__REQUIRED__",
                "stats_file": "__OPTIONAL__"}

input_params = {"config": "__OPTIONAL__",
                "sift": "__OPTIONAL__",
                "fork": "__OPTIONAL__",
                "species": "__OPTIONAL__",
                "assembly": "__OPTIONAL__",
                "format": "__OPTIONAL__",
                "html": "__OPTIONAL__",
                "fasta": "__OPTIONAL__",
                "sift": "__OPTIONAL__",
                "polyphen": "__OPTIONAL__",
                "custom": "__OPTIONAL__",
                "plugin": "__OPTIONAL__",
                "individual": "__OPTIONAL__",
                "vcf_info_field": "__OPTIONAL__",
                "terms": "__OPTIONAL__",
                "shift_hgvs": "__OPTIONAL__",
                "fields": "__OPTIONAL__",
                "convert": "__OPTIONAL__",
                "chr": "__OPTIONAL__",
                "pick_order": "__OPTIONAL__",
                "freq_pop": "__OPTIONAL__",
                "freq_freq": "__OPTIONAL__",
                "freq_gt_lt": "__OPTIONAL__",
                "freq_filter": "__OPTIONAL__",
                "host": "__OPTIONAL__",
                "user": "__OPTIONAL__",
                "password": "__OPTIONAL__",
                "port": "__OPTIONAL__",
                "db_version": "__OPTIONAL__",
                "registry": "__OPTIONAL__",
                "buffer_size": "__OPTIONAL__",
                "build": "__OPTIONAL__",
                "build": "__OPTIONAL__",
                "compress": "__OPTIONAL__",
                "cache_region_size": "__OPTIONAL__",
                "verbose": "__FLAG__",
                "quiet": "__FLAG__",
                "no_progress": "__FLAG__",
                "everything": "__FLAG__",
                "force_overwrite": "__FLAG__",
                "force": "__FLAG__",
                "no_stats": "__FLAG__",
                "stats_text": "__FLAG__",
                "cache": "__FLAG__",
                "offline": "__FLAG__",
                "cache_version": "__FLAG__",
                "show_cache_info": "__FLAG__",
                "variant_class": "__FLAG__",
                "poly": "__FLAG__",
                "humdiv": "__FLAG__",
                "regulatory": "__FLAG__",
                "cell_type": "__FLAG__",
                "phased": "__FLAG__",
                "allele_number": "__FLAG__",
                "total_length": "__FLAG__",
                "numbers": "__FLAG__",
                "domains": "__FLAG__",
                "no_escape": "__FLAG__",
                "keep_csq": "__FLAG__",
                "hgvs": "__FLAG__",
                "protein": "__FLAG__",
                "symbol": "__FLAG__",
                "ccds": "__FLAG__",
                "uniprot": "__FLAG__",
                "tsl": "__FLAG__",
                "canonical": "__FLAG__",
                "biotype": "__FLAG__",
                "xref_refseq": "__FLAG__",
                "check_existing": "__FLAG__",
                "check_alleles": "__FLAG__",
                "check_svs": "__FLAG__",
                "gmaf": "__FLAG__",
                "maf_1kg": "__FLAG__",
                "maf_esp": "__FLAG__",
                "old_maf": "__FLAG__",
                "pubmed": "__FLAG__",
                "failed": "__FLAG__",
                "vcf": "__FLAG__",
                "json": "__FLAG__",
                "gvf": "__FLAG__",
                "minimal": "__FLAG__",
                "check_ref": "__FLAG__",
                "coding_only": "__FLAG__",
                "no_intergenic": "__FLAG__",
                "pick": "__FLAG__",
                "pick_allele": "__FLAG__",
                "flag_pick": "__FLAG__",
                "flag_pick_allele": "__FLAG__",
                "per_gene": "__FLAG__",
                "most_severe": "__FLAG__",
                "summary": "__FLAG__",
                "filter_common": "__FLAG__",
                "check_frequency": "__FLAG__",
                "allow_non_variant": "__FLAG__",
                "database": "__FLAG__",
                "pass": "__FLAG__",
                "genomes": "__FLAG__",
                "gencode_basic": "__FLAG__",
                "refseq": "__FLAG__",
                "merged": "__FLAG__",
                "all_refseq": "__FLAG__",
                "lrg": "__FLAG__",
                "db": "__FLAG__",
                "no_whole_genome": "__FLAG__",
                "write_cache": "__FLAG__",
                "skip_db_check": "__FLAG__"}

return_value = []
