__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: 
    date_last_updated: 
    factory_version: '1.12.0'
__GENERAL__: 
    gatk_binary: '__REQUIRED__'
    java_binary: '__REQUIRED__'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'gatk_haplotype_caller'
        component_version: 'v1.0.0'
        seed_version: '3.4-0'
    run: 
        # NOTE: component cannot run in parallel mode.
        use_cluster: False
        memory: '6G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            intervals: '__OPTIONAL__'
            BQSR: '__OPTIONAL__'
            input_file: '__REQUIRED__'
            alleles: '__OPTIONAL__'
            dbsnp: '__OPTIONAL__'
            read_group_black_list: '__OPTIONAL__'
            excludeIntervals: '__OPTIONAL__'
            activeRegionIn: '__OPTIONAL__'
            comp: '__OPTIONAL__'
            reference_sequence: '__REQUIRED__'
        output_files: 
            log_to_file: '__OPTIONAL__'
            activityProfileOut: '__OPTIONAL__'
            bamOutput: '__OPTIONAL__'
            activeRegionOut: '__OPTIONAL__'
            graphOutput: '__OPTIONAL__'
            out: '__REQUIRED__'
        parameters: 
            indelSizeToEliminateInRefModel: '__OPTIONAL__'
            simplifyBAM: '__FLAG__'
            kmerSize: '__OPTIONAL__'
            minDanglingBranchLength: '__OPTIONAL__'
            contamination_fraction_per_sample_file: '__OPTIONAL__'
            analysis_type: 'HaplotypeCaller'
            min_base_quality_score: '__OPTIONAL__'
            group: '__OPTIONAL__'
            pcr_indel_model: '__OPTIONAL__'
            activeRegionExtension: '__OPTIONAL__'
            sample_name: '__OPTIONAL__'
            baq: '__OPTIONAL__'
            nonDeterministicRandomSeed: '__FLAG__'
            quantize_quals: '__OPTIONAL__'
            annotateNDA: '__FLAG__'
            preserve_qscores_less_than: '__OPTIONAL__'
            refactor_NDN_cigar_string: '__FLAG__'
            heterozygosity: '__OPTIONAL__'
            downsample_to_coverage: '__OPTIONAL__'
            disable_indel_quals: '__FLAG__'
            disable_read_filter: '__OPTIONAL__'
            pedigreeString: '__OPTIONAL__'
            emit_original_quals: '__FLAG__'
            showFullBamList: '__FLAG__'
            consensus: '__FLAG__'
            minReadsPerAlignmentStart: '__OPTIONAL__'
            allSitePLs: '__FLAG__'
            debug: '__FLAG__'
            variant_index_parameter: '__OPTIONAL__'
            remove_program_records: '__FLAG__'
            defaultBaseQualities: '__OPTIONAL__'
            downsample_to_fraction: '__OPTIONAL__'
            indel_heterozygosity: '__OPTIONAL__'
            dontIncreaseKmerSizesForCycles: '__FLAG__'
            gatk_key: '__OPTIONAL__'
            activeRegionMaxSize: '__OPTIONAL__'
            allowNonUniqueKmersInRef: '__FLAG__'
            pedigree: '__OPTIONAL__'
            interval_set_rule: '__OPTIONAL__'
            forceActive: '__FLAG__'
            contamination_fraction_to_filter: '__OPTIONAL__'
            sample_rename_mapping_file: '__OPTIONAL__'
            useFilteredReadsForAnnotations: '__FLAG__'
            maxRuntime: '__OPTIONAL__'
            output_mode: '__OPTIONAL__'
            arg_file: '__OPTIONAL__'
            bam_compression: '__OPTIONAL__'
            validation_strictness: '__OPTIONAL__'
            variant_index_type: '__OPTIONAL__'
            downsampling_type: '__OPTIONAL__'
            sample_ploidy: '__OPTIONAL__'
            doNotRunPhysicalPhasing: '__FLAG__'
            read_filter: '__OPTIONAL__'
            emitRefConfidence: '__OPTIONAL__'
            max_alternate_alleles: '__OPTIONAL__'
            pedigreeValidationType: '__OPTIONAL__'
            performanceLog: '__OPTIONAL__'
            baqGapOpenPenalty: '__OPTIONAL__'
            useOriginalQualities: '__FLAG__'
            fix_misencoded_quality_scores: '__FLAG__'
            interval_merging: '__OPTIONAL__'
            generate_md5: '__FLAG__'
            useAllelesTrigger: '__FLAG__'
            annotation: '__OPTIONAL__'
            disableOptimizations: '__FLAG__'
            minPruning: '__OPTIONAL__'
            num_threads: '__OPTIONAL__'
            unsafe: '__OPTIONAL__'
            numPruningSamples: '__OPTIONAL__'
            allow_potentially_misencoded_quality_scores: '__FLAG__'
            java_memory: '5G'
            bamWriterType: '__OPTIONAL__'
            input_prior: '__OPTIONAL__'
            bandPassSigma: '__OPTIONAL__'
            standard_min_confidence_threshold_for_calling: '__OPTIONAL__'
            activeProbabilityThreshold: '__OPTIONAL__'
            never_trim_vcf_format_field: '__FLAG__'
            num_bam_file_handles: '__OPTIONAL__'
            maxRuntimeUnits: '__OPTIONAL__'
            gcpHMM: '__OPTIONAL__'
            tag: '__OPTIONAL__'
            maxReadsInRegionPerSample: '__OPTIONAL__'
            sites_only: '__FLAG__'
            disable_bam_indexing: '__FLAG__'
            standard_min_confidence_threshold_for_emitting: '__OPTIONAL__'
            dontUseSoftClippedBases: '__FLAG__'
            num_cpu_threads_per_data_thread: '__OPTIONAL__'
            logging_level: '__OPTIONAL__'
            excludeAnnotation: '__OPTIONAL__'
            GVCFGQBands: '__OPTIONAL__'
            read_buffer_size: '__OPTIONAL__'
            interval_padding: '__OPTIONAL__'
            dontTrimActiveRegions: '__FLAG__'
            globalQScorePrior: '__OPTIONAL__'
            genotyping_mode: '__OPTIONAL__'
            keep_program_records: '__FLAG__'
            phredScaledGlobalReadMismappingRate: '__OPTIONAL__'
            phone_home: '__OPTIONAL__'
            monitorThreadEfficiency: '__FLAG__'
            maxNumHaplotypesInPopulation: '__OPTIONAL__'
