"""
component_params.py

@author: bgrande
"""


input_files = {"input_file": "__REQUIRED__",
               "alleles": "__OPTIONAL__",
               "dbsnp": "__OPTIONAL__",
               "activeRegionIn": "__OPTIONAL__",
               "comp": "__OPTIONAL__",
               "intervals": "__OPTIONAL__",
               "excludeIntervals": "__OPTIONAL__",
               "reference_sequence": "__REQUIRED__",
               "BQSR": "__OPTIONAL__",
               "read_group_black_list": "__OPTIONAL__"}

output_files = {"activeRegionOut": "__OPTIONAL__",
                "activityProfileOut": "__OPTIONAL__",
                "graphOutput": "__OPTIONAL__",
                "out": "__REQUIRED__",
                "bamOutput": "__OPTIONAL__",
                "log_to_file": "__OPTIONAL__"}

input_params = {"analysis_type": "HaplotypeCaller",
                "java_memory": "5G",
                "contamination_fraction_to_filter": "__OPTIONAL__",
                "genotyping_mode": "__OPTIONAL__",
                "group": "__OPTIONAL__",
                "heterozygosity": "__OPTIONAL__",
                "indel_heterozygosity": "__OPTIONAL__",
                "maxReadsInRegionPerSample": "__OPTIONAL__",
                "min_base_quality_score": "__OPTIONAL__",
                "minReadsPerAlignmentStart": "__OPTIONAL__",
                "output_mode": "__OPTIONAL__",
                "sample_name": "__OPTIONAL__",
                "sample_ploidy": "__OPTIONAL__",
                "standard_min_confidence_threshold_for_calling": "__OPTIONAL__",
                "standard_min_confidence_threshold_for_emitting": "__OPTIONAL__",
                "annotateNDA": "__FLAG__",
                "activeProbabilityThreshold": "__OPTIONAL__",
                "activeRegionExtension": "__OPTIONAL__",
                "activeRegionMaxSize": "__OPTIONAL__",
                "annotation": "__OPTIONAL__",
                "bamWriterType": "__OPTIONAL__",
                "bandPassSigma": "__OPTIONAL__",
                "contamination_fraction_per_sample_file": "__OPTIONAL__",
                "emitRefConfidence": "__OPTIONAL__",
                "excludeAnnotation": "__OPTIONAL__",
                "gcpHMM": "__OPTIONAL__",
                "GVCFGQBands": "__OPTIONAL__",
                "indelSizeToEliminateInRefModel": "__OPTIONAL__",
                "input_prior": "__OPTIONAL__",
                "kmerSize": "__OPTIONAL__",
                "max_alternate_alleles": "__OPTIONAL__",
                "maxNumHaplotypesInPopulation": "__OPTIONAL__",
                "minDanglingBranchLength": "__OPTIONAL__",
                "minPruning": "__OPTIONAL__",
                "numPruningSamples": "__OPTIONAL__",
                "pcr_indel_model": "__OPTIONAL__",
                "phredScaledGlobalReadMismappingRate": "__OPTIONAL__",
                "allowNonUniqueKmersInRef": "__FLAG__",
                "allSitePLs": "__FLAG__",
                "consensus": "__FLAG__",
                "debug": "__FLAG__",
                "disableOptimizations": "__FLAG__",
                "doNotRunPhysicalPhasing": "__FLAG__",
                "dontIncreaseKmerSizesForCycles": "__FLAG__",
                "dontTrimActiveRegions": "__FLAG__",
                "dontUseSoftClippedBases": "__FLAG__",
                "forceActive": "__FLAG__",
                "useAllelesTrigger": "__FLAG__",
                "useFilteredReadsForAnnotations": "__FLAG__",
                "arg_file": "__OPTIONAL__",
                "showFullBamList": "__FLAG__",
                "read_buffer_size": "__OPTIONAL__",
                "phone_home": "__OPTIONAL__",
                "gatk_key": "__OPTIONAL__",
                "tag": "__OPTIONAL__",
                "read_filter": "__OPTIONAL__",
                "disable_read_filter": "__OPTIONAL__",
                "interval_set_rule": "__OPTIONAL__",
                "interval_merging": "__OPTIONAL__",
                "interval_padding": "__OPTIONAL__",
                "nonDeterministicRandomSeed": "__FLAG__",
                "maxRuntime": "__OPTIONAL__",
                "maxRuntimeUnits": "__OPTIONAL__",
                "downsampling_type": "__OPTIONAL__",
                "downsample_to_fraction": "__OPTIONAL__",
                "downsample_to_coverage": "__OPTIONAL__",
                "baq": "__OPTIONAL__",
                "baqGapOpenPenalty": "__OPTIONAL__",
                "refactor_NDN_cigar_string": "__FLAG__",
                "fix_misencoded_quality_scores": "__FLAG__",
                "allow_potentially_misencoded_quality_scores": "__FLAG__",
                "useOriginalQualities": "__FLAG__",
                "defaultBaseQualities": "__OPTIONAL__",
                "performanceLog": "__OPTIONAL__",
                "quantize_quals": "__OPTIONAL__",
                "disable_indel_quals": "__FLAG__",
                "emit_original_quals": "__FLAG__",
                "preserve_qscores_less_than": "__OPTIONAL__",
                "globalQScorePrior": "__OPTIONAL__",
                "validation_strictness": "__OPTIONAL__",
                "remove_program_records": "__FLAG__",
                "keep_program_records": "__FLAG__",
                "sample_rename_mapping_file": "__OPTIONAL__",
                "unsafe": "__OPTIONAL__",
                "sites_only": "__FLAG__",
                "never_trim_vcf_format_field": "__FLAG__",
                "bam_compression": "__OPTIONAL__",
                "simplifyBAM": "__FLAG__",
                "disable_bam_indexing": "__FLAG__",
                "generate_md5": "__FLAG__",
                "num_threads": "__OPTIONAL__",
                "num_cpu_threads_per_data_thread": "__OPTIONAL__",
                "monitorThreadEfficiency": "__FLAG__",
                "num_bam_file_handles": "__OPTIONAL__",
                "pedigree": "__OPTIONAL__",
                "pedigreeString": "__OPTIONAL__",
                "pedigreeValidationType": "__OPTIONAL__",
                "variant_index_type": "__OPTIONAL__",
                "variant_index_parameter": "__OPTIONAL__",
                "logging_level": "__OPTIONAL__"}

return_value = []
