__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: 
    date_last_updated: 
    factory_version: '1.12.0'
__GENERAL__: 
    samtools: 'samtools'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    input_bam: unsorted_bam1

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'samtools_sort_parallelized'
        component_version: 'v1.0.0'
        seed_version: 'v1.2'
    run: 
        use_cluster: False
        memory: '6G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            input_bam: '__REQUIRED__'
        output_files: 
            output_bam: '__REQUIRED__'
        parameters: 
        "l": "__OPTIONAL__",
                "m": "__OPTIONAL__"
                "n": "__FLAG__"
                "o": "__OPTIONAL__"
                "O": "__OPTIONAL__"
                "T": "__OPTIONAL__"
                "@": "__OPTIONAL__"
