__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: '2015-12-16'
    date_last_updated: 
    Kronos_version: '2.0.3'
__GENERAL__: 
    samtools: 'samtools'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'samtools_sort_parallelized'
        component_version: 'v1.0.0'
        seed_version: 'v1.2'
    run: 
        use_cluster: False
        memory: '6G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
        parallel_run: False
        parallel_params: []
        interval_file: 
    component: 
        input_files: 
            input_dir: '__REQUIRED__'
        output_files: 
            output_dir: '__REQUIRED__'
        parameters: 
            o: '__OPTIONAL__'
            @: '__OPTIONAL__'
            m: '__OPTIONAL__'
            l: '__OPTIONAL__'
            O: '__OPTIONAL__'
            T: '__OPTIONAL__'
            'n': '__FLAG__'
