__PIPELINE_INFO__:
    name:
    version:
    author:
    data_type:
    input_type:
    output_type:
    host_cluster:
    date_created:
    date_last_updated:
    factory_version: '1.12.0'
__GENERAL__:
    bwa: 'bwa'
    samtools: 'samtools'
__SHARED__:
__SAMPLES__:
    # sample_id:
    #    bam: bam1
__TASK_1__:
    reserved:
        # do not change this section.
        component_name: 'samtools_mpileup'
        component_version: 'v1.0.0'
        seed_version: 'v1.2'
    run:
        use_cluster: True
        memory: '6G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars:
        boilerplate:
        parallel_run: True
        parallel_params: []
        interval_file:
    component:
        input_files:
            input_bam: '__REQUIRED__'
        output_files:
            output_file: '__REQUIRED__'
        parameters:
            "f":"__REQUIRED__"
            "6":"__FLAG__"
            "A":"__FLAG__"
            "B":"__FLAG__"
            "b":"__OPTIONAL__"
            "C":"__OPTIONAL__"
            "d":"__OPTIONAL__"
            "E":"__FLAG__"
            "G":"__OPTIONAL__"
            "l":"__OPTIONAL__"
            "M":"__OPTIONAL__"
            "r":"__OPTIONAL__"
            "R":"__FLAG__"
            "q":"__OPTIONAL__"
            "Q":"__OPTIONAL__"
            "rf":"__OPTIONAL__"
            "ff":"__OPTIONAL__"
            "D":"__FLAG__"
            "g":"__FLAG__"
            "O":"__FLAG__"
            "s":"__FLAG__"
            "S":"__FLAG__"
            "u":"__FLAG__"
            "e":"__OPTIONAL__"
            "F":"__OPTIONAL__"
            "h":"__OPTIONAL__"
            "I":"__FLAG__"
            "L":"__OPTIONAL__"
            "m":"__OPTIONAL__"
            "o":"__OPTIONAL__"
            "p":"__FLAG__"
            "P":"__OPTIONAL__"
