__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: 
    date_last_updated: 
    factory_version: '1.12.0'
__GENERAL__: 
    samtools: 'samtools'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'samtools_mpileup'
        component_version: 'v1.0.0'
        seed_version: 'v1.2'
    run: 
        use_cluster: False
        memory: '6G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
        parallel_run: False
        parallel_params: []
        interval_file: 
    component: 
        input_files: 
            input_bam: '__REQUIRED__'
        output_files: 
            output_file: '__REQUIRED__'
        parameters: 
            A: '__FLAG__'
            C: '__OPTIONAL__'
            B: '__FLAG__'
            E: '__FLAG__'
            D: '__FLAG__'
            G: '__OPTIONAL__'
            F: '__OPTIONAL__'
            I: '__FLAG__'
            s: '__FLAG__'
            M: '__OPTIONAL__'
            L: '__OPTIONAL__'
            O: '__FLAG__'
            Q: '__OPTIONAL__'
            P: '__OPTIONAL__'
            S: '__FLAG__'
            R: '__FLAG__'
            ff: '__OPTIONAL__'
            b: '__OPTIONAL__'
            e: '__OPTIONAL__'
            d: '__OPTIONAL__'
            g: '__FLAG__'
            f: '__OPTIONAL__'
            h: '__OPTIONAL__'
            m: '__OPTIONAL__'
            l: '__OPTIONAL__'
            o: '__OPTIONAL__'
            q: '__OPTIONAL__'
            p: '__FLAG__'
            rf: '__OPTIONAL__'
            r: '__OPTIONAL__'
            u: '__FLAG__'
            6: '__FLAG__'
