__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: '2016-01-08'
    date_last_updated: 
    Kronos_version: '2.0.3'
__GENERAL__: 
    gzip: '__OPTIONAL__'
    samtools: '__REQUIRED__'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'samtools_mpileup'
        component_version: 'v1.0.0'
        seed_version: '1.2.0'
    run: 
        # NOTE: component cannot run in parallel mode.
        use_cluster: False
        memory: '1G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            fasta_ref: '__OPTIONAL__'
            exclude_RG: '__OPTIONAL__'
            bam_list: '__OPTIONAL__'
            input_bam: '__REQUIRED__'
            positions: '__OPTIONAL__'
        output_files: 
            output: '__REQUIRED__'
        parameters: 
            BCF: '__FLAG__'
            excl_flags: '__OPTIONAL__'
            skip_indels: '__FLAG__'
            ignore_overlaps: '__FLAG__'
            redo_BAQ: '__FLAG__'
            gap_frac: '__OPTIONAL__'
            uncompressed: '__FLAG__'
            incl_flags: '__OPTIONAL__'
            max_depth: '__OPTIONAL__'
            tandem_qual: '__OPTIONAL__'
            adjust_MQ: '__OPTIONAL__'
            compress_pileup: '__FLAG__'
            VCF: '__FLAG__'
            count_orphans: '__FLAG__'
            open_prob: '__OPTIONAL__'
            max_idepth: '__OPTIONAL__'
            illumina1.3+: '__FLAG__'
            output_MQ: '__FLAG__'
            output_tags: '__OPTIONAL__'
            ext_prob: '__OPTIONAL__'
            ignore_RG: '__FLAG__'
            platforms: '__OPTIONAL__'
            min_BQ: '__OPTIONAL__'
            region: '__OPTIONAL__'
            min_MQ: '__OPTIONAL__'
            min_ireads: '__OPTIONAL__'
            per_sample_mF: '__FLAG__'
            no_BAQ: '__FLAG__'
            output_BP: '__FLAG__'
