__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: 
    date_last_updated: 
    factory_version: '1.11.2'
__GENERAL__: 
    samtools: '/path/to/samtools/'
    java: 'java'
    picardtools: '/path/to/picardtools/'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'filter_bam'
        component_version: '1.0.0'
        seed_version: '1.1'
    run: 
        # NOTE: component cannot run in parallel mode.
        use_cluster: False
        memory: '5G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            input_bam: '__REQUIRED__'
        output_files: 
            output_paired: '__REQUIRED__'
            output_readnames: '__REQUIRED__'
            output_unpaired: '__REQUIRED__'
        parameters: 
            verbosity: 'INFO'
            delete_input: 'false'
            quiet: 'false'
            val_stringency: 'STRICT'
            sort_order: 'coordinate'
            java_mem: '4G'
