__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: '2016-01-08'
    date_last_updated: 
    Kronos_version: '2.0.3'
__GENERAL__: 
    python: 'python'
    check_read_names: 'check_read_names'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'check_read_names'
        component_version: 'v1.0.0'
        seed_version: 'v1.0'
    run: 
        # NOTE: component cannot run in parallel mode.
        use_cluster: False
        memory: '24G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            original_bam: '__OPTIONAL__'
            read_set: '__OPTIONAL__'
            new_fastq_filename: '__OPTIONAL__'
            new_bam_filename: '__OPTIONAL__'
        output_files: 
            read_set_out: '__OPTIONAL__'
        parameters: 
            files_to_delete: '__OPTIONAL__'
            new_file_path: '__OPTIONAL__'
            files_to_delete_path: '__OPTIONAL__'
