__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: 
    date_last_updated: 
    factory_version: '1.12.0'
__GENERAL__: 
    python: '/home/jgrewal/software/anaconda/bin/python'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'augmentmaf'
        component_version: '1.00.0'
        seed_version: '1.00.0'
    run: 
        # NOTE: component cannot run in parallel mode.
        use_cluster: False
        memory: '5G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            input_maf: '__REQUIRED__'
            input_nbam: '__REQUIRED__'
            input_tbam: '__REQUIRED__'
            reference: '__REQUIRED__'
        output_files: 
            output_augmaf: '__REQUIRED__'
        parameters: 
