""" 
component_main.py
This module contains Component class which extends 
the ComponentAbstract class. It is the core of a component.

@author: jgrewal
@Date Created: 16 March 2015
@Date Modified: 16 March 2015
"""

from pipeline_factory.utils import ComponentAbstract
import os

class Component(ComponentAbstract):
    
    """
	This component takes a maf file generated by vcf2maf, and generated an augmaf'd output with allelic counts.
	Input:
		-input maf file. Required.
		-input Normal Bam file. Required.
		-input Tumour Bam file. Required.
		-input reference. Required.
		-output file name for augmaf'd result. Required.
    """

    def __init__(self, component_name="augmentmaf", 
                 component_parent_dir=None, seed_dir=None):
        
        ## pass the version of the component here.
        self.version = "v1.00.0"

        ## initialize ComponentAbstract
        super(Component, self).__init__(component_name, 
                                        component_parent_dir, seed_dir)

    ##  write the focus method if the component is parallelizable.
    ## Note that it should return cmd, cmd_args.
    def focus(self, cmd, cmd_args, chunk):
        pass 
#         return cmd, cmd_args

    ## this method should make the command and command arguments 
    ## used to run the component_seed via the command line. Note that 
    ## it should return cmd, cmd_args. 
    def make_cmd(self, chunk=None):
	path=os.path.join(self.seed_dir,'augment_maf.py')
	cmd=self.requirements["python"] + path
	cmd_args=["-n "+self.args.input_nbam, "-t "+self.args.input_tbam, "-m "+self.args.input_maf, self.args.reference, self.args.output_augmaf]
	return cmd, cmd_args

## To run as stand alone
def _main():
    m = Component()
    m.args = component_ui.args
    m.run()

if __name__ == '__main__':
    import component_ui
    _main()

