__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: 
    date_last_updated: 
    factory_version: '1.12.0'
__GENERAL__: 
    bamhash_checksum_bam: 'bamhash_checksum_bam'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    in_bam: bam1

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'bamhash_checksum_bam'
        component_version: 'v1.0.0'
        seed_version: 'v1.1'
    run: 
        use_cluster: False
        memory: '1G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
        parallel_run: False
        parallel_params: []
        interval_file: 
    component: 
        input_files: 
            in_bams: '__REQUIRED__'
        output_files: 
            out_checksum: '__REQUIRED__'
        parameters: 
            d: '__FLAG__'
            R: '__FLAG__'
            Q: '__FLAG__'
            P: '__FLAG__'
