__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: '2016-01-08'
    date_last_updated: 
    Kronos_version: '2.0.3'
__GENERAL__: 
    samtools: 'samtools'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'samtools_merge'
        component_version: 'v1.0.0'
        seed_version: 'v1.2'
    run: 
        # NOTE: component cannot run in parallel mode.
        use_cluster: False
        memory: '6G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            input_dir: '__REQUIRED__'
        output_files: 
            output_file: '__REQUIRED__'
        parameters: 
            1: '__FLAG__'
            p: '__FLAG__'
            c: '__FLAG__'
            b: '__OPTIONAL__'
            u: '__FLAG__'
            f: '__FLAG__'
            h: '__OPTIONAL__'
            R: '__OPTIONAL__'
            r: '__FLAG__'
