__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: 
    date_last_updated: 
    factory_version: '1.12.0'
__GENERAL__: 
    python: 'python'
    hash_qname_and_cleanup: 'hash_qname_and_cleanup.py'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'hash_qname_and_cleanup'
        component_version: 'v1.0.0'
        seed_version: 'v1.0'
    run: 
        use_cluster: True
        memory: '24G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        parallel_run: False 
    component:
        input_files:
            original_bam: '__OPTIONAL__'
            read_set: '__OPTIONAL__'
            new_fastq_filename: '__OPTIONAL__'
            new_bam_filename: '__OPTIONAL__'
        output_files:
            read_set_out: '__OPTIONAL__'
        parameters: 
            new_file_path: '__OPTIONAL__'
            files_to_delete_path: '__OPTIONAL__'
            files_to_delete: '__OPTIONAL__'
