__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: 
    date_last_updated: 
    factory_version: '1.12.0'
__GENERAL__: 
    python: '__REQUIRED__'
    sequenza-utils.py: '__REQUIRED__'
    samtools: '__REQUIRED__'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'sequenza_bam2seqz'
        component_version: 'v1.0.0'
        seed_version: '2.1.0'
    run: 
        # NOTE: component cannot run in parallel mode.
        use_cluster: False
        memory: '1G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            tumor: '__REQUIRED__'
            fasta: '__REQUIRED__'
            gc: '__REQUIRED__'
            normal2: '__OPTIONAL__'
            normal: '__REQUIRED__'
        output_files: 
            output: '__REQUIRED__'
        parameters: 
            het: '__OPTIONAL__'
            hom: '__OPTIONAL__'
            qformat: '__OPTIONAL__'
            'N': '__OPTIONAL__'
            compress_seqz: '__FLAG__'
            qlimit: '__OPTIONAL__'
            chromosome: '__OPTIONAL__'
