__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: '2016-06-09'
    date_last_updated: 
    Kronos_version: '2.1.0'
__GENERAL__: 
    make: 'make'
    configureStrelkaWorkflow.pl: '__REQUIRED__'
    perl: 'perl'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'strelka'
        component_version: 'v1.0.0'
        seed_version: 'v1.0.14'
    run: 
        # NOTE: component cannot run in parallel mode.
        use_cluster: False
        memory: '1G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            config_file: '__REQUIRED__'
            reference: '__REQUIRED__'
            normal_bam: '__REQUIRED__'
            tumour_bam: '__REQUIRED__'
        output_files: 
            passed_snvs_vcf: '__REQUIRED__'
            output_dir: '__REQUIRED__'
            passed_indels_vcf: '__REQUIRED__'
        parameters: 
            num_threads: '__OPTIONAL__'
