__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: '2016-07-01'
    date_last_updated: 
    Kronos_version: '2.1.0'
__GENERAL__: 
    bwa: 'bwa'
    samtools: 'samtools'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'bwa_mem_parallelized'
        component_version: 'v1.0.0'
        seed_version: 'v0.7.10'
    run: 
        use_cluster: False
        memory: '6G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
        parallel_run: False
        parallel_params: []
        interval_file: 
    component: 
        input_files: 
            input_dir: '__REQUIRED__'
            bwa_index_prefix: '__REQUIRED__'
        output_files: 
            output_dir: '__REQUIRED__'
        parameters: 
            A: '__OPTIONAL__'
            a: '__FLAG__'
            c: '__OPTIONAL__'
            B: '__OPTIONAL__'
            E: '__OPTIONAL__'
            d: '__OPTIONAL__'
            p: '__FLAG__'
            C: '__FLAG__'
            H: '__FLAG__'
            k: '__OPTIONAL__'
            M: '__FLAG__'
            L: '__OPTIONAL__'
            O: '__OPTIONAL__'
            P: '__FLAG__'
            r: '__OPTIONAL__'
            U: '__OPTIONAL__'
            t: '__OPTIONAL__'
            w: '__OPTIONAL__'
            v: '__OPTIONAL__'
            R: '__OPTIONAL__'
            T: '__OPTIONAL__'
