__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: '2015-12-16'
    date_last_updated: 
    Kronos_version: '2.0.3'
__GENERAL__: 
    delly: 'delly'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'delly'
        component_version: 'v1.0.0'
        seed_version: 'v0.6.3'
    run: 
        # NOTE: component cannot run in parallel mode.
        use_cluster: False
        memory: '4G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            bam_files: '__REQUIRED__'
        output_files: 
            vcf_file: '__REQUIRED__'
        parameters: 
            num_threads: '__OPTIONAL__'
            reference_fasta: '__REQUIRED__'
            vcfgeno: '__OPTIONAL__'
            excluded_regions: '__OPTIONAL__'
            sv_type: '__REQUIRED__'
            geno_qual: '__OPTIONAL__'
            map_qual: '__OPTIONAL__'
            min_flank: '__OPTIONAL__'
            mad_cutoff: '__OPTIONAL__'
