__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: 
    date_last_updated: 
    factory_version: '1.11.2'
__GENERAL__: 
    python: 'python'
    convert_files.py: '__REQUIRED__'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'convert_files'
        component_version: 'v1.0.0'
        seed_version: 'v1.0.0'
    run: 
        # NOTE: component cannot run in parallel mode.
        use_cluster: False
        memory: '1G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            input_files: '__REQUIRED__'
        output_files: 
            output_dir: '__OPTIONAL__'
        parameters: 
            input_type: '__REQUIRED__'
            input_parser: '__REQUIRED__'
            output_type: '__REQUIRED__'
