__PIPELINE_INFO__: 
    name: bam2fq
    version: 1.0.0
    author: ppararaj
    data_type: null
    input_type: bam
    output_type: directory
    host_cluster: genesis
    date_created: Oct 21 2015
    date_last_updated: Oct 21 2015
    factory_version: '1.12.0'
__GENERAL__: 
    python: 'python'
    samtools: 'samtools'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    bam: value1

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'bam2fq'
        component_version: 'v1.0.0'
        seed_version: 'v1.0.0'
    run: 
        use_cluster: False
        memory: '6G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
        parallel_run: False
        parallel_params: []
        interval_file: 
    component: 
        input_files: 
            bam: ('__SAMPLES__', bam)
        output_files: 
            outdir: '__REQUIRED__'
        parameters: 
            num_reads: '__OPTIONAL__'
