__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: 
    date_last_updated: 
    factory_version: '1.12.0'
__GENERAL__: 
    python: 'python'
    somaticFilter.py: '__REQUIRED__'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'delly_somatic_filter'
        component_version: 'v1.0.0'
        seed_version: '1.0.0'
    run: 
        # NOTE: component cannot run in parallel mode.
        use_cluster: False
        memory: '1G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            vcfFile: '__OPTIONAL__'
        output_files: 
            outFile: '__OPTIONAL__'
        parameters: 
            siteFilter: False
            minSize: '__OPTIONAL__'
            svType: '__OPTIONAL__'
            maxSize: '__OPTIONAL__'
            ratioGeno: '__OPTIONAL__'
            altAF: '__OPTIONAL__'
