__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: '2016-01-08'
    date_last_updated: 
    Kronos_version: '2.0.3'
__GENERAL__: 
    java: '/gsc/software/linux-x86_64-centos5/java-1.7.0-u13/bin/'
    picardtools: '/home/jgrewal/software/picard/picard-tools-1.119/'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'picard_samtofastq'
        component_version: 'v3.0'
        seed_version: 'version 1.119'
    run: 
        use_cluster: False
        memory: '4G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
        parallel_run: False
        parallel_params: []
        interval_file: 
    component: 
        input_files: 
            input_bam: '__REQUIRED__'
        output_files: 
            outfile2: '__OPTIONAL__'
            outfile1: '__OPTIONAL__'
            output_dir: './'
            log_file: 'samToFastq_run.log'
        parameters: 
            include_nonprimary: 'false'
            clipping_attribute: 'null'
            val_stringency: 'SILENT'
            tmp_dir: 'null'
            verbosity: 'INFO'
            javamem: '4G'
            quiet: 'false'
            output_per_rg: 'false'
            read2_trim: '0'
            no_compression: False
            interleave: 'false'
            rg_tag: 'PU'
            clipping_action: 'null'
            read1_trim: '0'
            include_non_pf_reads: 'false'
            rereverse_bases: 'false'
            read1_maxbases: 'null'
            read2_maxbases: 'null'
