__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: 
    date_last_updated: 
    factory_version: '1.12.0'
__GENERAL__: 
    python: 'python'
    generate_sequenza_output.py: '__REQUIRED__'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'sequenza'
        component_version: 'v1.0.0'
        seed_version: '2.1.2'
    run: 
        # NOTE: component cannot run in parallel mode.
        use_cluster: False
        memory: '10G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            ref_fa: '__REQUIRED__'
            input_normal_bam: '__REQUIRED__'
            input_tumour_bam: '__REQUIRED__'
            seq_utils: '__REQUIRED__'
            seq_analyze: '__REQUIRED__'
            gc_ref: '__REQUIRED__'
        output_files: 
            output_dir: '__REQUIRED__'
        parameters: 
            gender: '__OPTIONAL__'
            sample_id: '__OPTIONAL__'
