__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: 
    date_last_updated: 
    factory_version: '1.12.0'
__GENERAL__: 
    python: '/path/python/bin/python'
    gatk: '/path/to/gatk'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'liftover_vcf'
        component_version: '1.00.0'
        seed_version: '3.3'
    run: 
        # NOTE: component cannot run in parallel mode.
        use_cluster: False
        memory: '5G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            input_vcf: '__REQUIRED__'
        output_files: 
            output_file: '__REQUIRED__'
        parameters: 
            old_ref: '__REQUIRED__'
            new_ref: '__REQUIRED__'
            chain_file: '__REQUIRED__'
