__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: '2016-01-08'
    date_last_updated: 
    Kronos_version: '2.0.3'
__GENERAL__: 
    gzip: 'gzip'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'gzip'
        component_version: 'v1.0.0'
        seed_version: 'v1.6'
    run: 
        # NOTE: component cannot run in parallel mode.
        use_cluster: False
        memory: '6G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            input_file: '__REQUIRED__'
        output_files: 
        parameters: 
