__PIPELINE_INFO__: 
    name: 
    version: 
    author: 
    data_type: 
    input_type: 
    output_type: 
    host_cluster: 
    date_created: '2015-12-16'
    date_last_updated: 
    Kronos_version: '2.0.3'
__GENERAL__: 
    gatk_binary: '__REQUIRED__'
    java_binary: '__REQUIRED__'
__SHARED__: 
__SAMPLES__: 
    # sample_id:
    #    param1: value1
    #    param2: value2

__TASK_1__: 
    reserved: 
        # do not change this section.
        component_name: 'gatk_base'
        component_version: 'v1.0.0'
        seed_version: '3.4-0'
    run: 
        # NOTE: component cannot run in parallel mode.
        use_cluster: False
        memory: '6G'
        num_cpus: 1
        forced_dependencies: []
        add_breakpoint: False
        env_vars: 
        boilerplate: 
    component: 
        input_files: 
            input_file: '__OPTIONAL__'
            intervals: '__OPTIONAL__'
            BQSR: '__OPTIONAL__'
            read_group_black_list: '__OPTIONAL__'
            excludeIntervals: '__OPTIONAL__'
            reference_sequence: '__OPTIONAL__'
        output_files: 
            log_to_file: '__OPTIONAL__'
        parameters: 
            monitorThreadEfficiency: '__FLAG__'
            useOriginalQualities: '__FLAG__'
            pedigreeValidationType: '__OPTIONAL__'
            simplifyBAM: '__FLAG__'
            performanceLog: '__OPTIONAL__'
            baqGapOpenPenalty: '__OPTIONAL__'
            java_memory: '5G'
            analysis_type: '__REQUIRED__'
            unsafe: '__OPTIONAL__'
            interval_merging: '__OPTIONAL__'
            generate_md5: '__FLAG__'
            baq: '__OPTIONAL__'
            nonDeterministicRandomSeed: '__FLAG__'
            quantize_quals: '__OPTIONAL__'
            preserve_qscores_less_than: '__OPTIONAL__'
            refactor_NDN_cigar_string: '__FLAG__'
            allow_potentially_misencoded_quality_scores: '__FLAG__'
            downsample_to_coverage: '__OPTIONAL__'
            disable_indel_quals: '__FLAG__'
            disable_read_filter: '__OPTIONAL__'
            pedigreeString: '__OPTIONAL__'
            defaultBaseQualities: '__OPTIONAL__'
            showFullBamList: '__FLAG__'
            variant_index_parameter: '__OPTIONAL__'
            never_trim_vcf_format_field: '__FLAG__'
            remove_program_records: '__FLAG__'
            emit_original_quals: '__FLAG__'
            num_bam_file_handles: '__OPTIONAL__'
            maxRuntimeUnits: '__OPTIONAL__'
            downsample_to_fraction: '__OPTIONAL__'
            tag: '__OPTIONAL__'
            sites_only: '__FLAG__'
            disable_bam_indexing: '__FLAG__'
            gatk_key: '__OPTIONAL__'
            pedigree: '__OPTIONAL__'
            maxRuntime: '__OPTIONAL__'
            interval_set_rule: '__OPTIONAL__'
            num_cpu_threads_per_data_thread: '__OPTIONAL__'
            sample_rename_mapping_file: '__OPTIONAL__'
            logging_level: '__OPTIONAL__'
            arg_file: '__OPTIONAL__'
            read_buffer_size: '__OPTIONAL__'
            interval_padding: '__OPTIONAL__'
            bam_compression: '__OPTIONAL__'
            globalQScorePrior: '__OPTIONAL__'
            validation_strictness: '__OPTIONAL__'
            num_threads: '__OPTIONAL__'
            variant_index_type: '__OPTIONAL__'
            downsampling_type: '__OPTIONAL__'
            keep_program_records: '__FLAG__'
            phone_home: '__OPTIONAL__'
            read_filter: '__OPTIONAL__'
            fix_misencoded_quality_scores: '__FLAG__'
